# Generated by Django 2.2.2 on 2020-06-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('isavailable', models.CharField(max_length=20)),
                ('isborrowed', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('privilige', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childuser', to='userModel.User')),
                ('upperuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upperuser', to='userModel.User')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBelonging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.User')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('extras', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.User')),
            ],
        ),
        migrations.CreateModel(
            name='OtherNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('isread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.User')),
            ],
        ),
    ]
