# Generated by Django 2.2.2 on 2020-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othernotice',
            name='isread',
            field=models.CharField(max_length=20),
        ),
    ]
